package com.leeco.eui.api.utils;

public enum ApplicationEvents {
	APPLICATION_ADDED,
	APPLICATION_UPDATED,
	APPLICATION_DELETED,
	CATEGORY_ADDED,
	CATEGORY_UPDATED,
	CATEGORY_DELETED,
	RECOMMENDATION_ADDED,
	RECOMMENDATION_DELETED,
	RECOMMENDATION_ORDER_CHANGED
}
